language: java
sudo: required
jdk: oraclejdk7
cache:
  directories:
    - $TRAVIS_BUILD_DIR/libraries
services:
  - postgresql
before_install:
  - sudo pip install codecov
install:
  - wget -P libraries/apache-ant-contrib/javalib/ http://central.maven.org/maven2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar
  - wget -P libraries/testng/javalib http://central.maven.org/maven2/org/testng/testng/6.9.10/testng-6.9.10.jar
  - mkdir ../document
  - cd ../document
  - wget https://github.com/servicecatalog/documentation/archive/master.zip
  - unzip master.zip
  - mv documentation-master/* .
  - cd ../development
  - wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.4-bin.tar.gz
  - tar -xvzf apache-ant-1.9.4-bin.tar.gz
env:
  global:
    - ANT_HOME="apache-ant-1.9.4"
    - ANT_OPTS=-Xmx4g
    - COMUPTERNAME=travis
    - HOSTNAME=travis
before_script:
  - psql -c "CREATE ROLE bssunituser LOGIN PASSWORD 'bssunituser';" -U postgres
  - psql -c "CREATE ROLE bssappunituser LOGIN PASSWORD 'bssappunituser';" -U postgres
script:
  - ant -lib $TRAVIS_BUILD_DIR/libraries/apache-ant-contrib/javalib -file $TRAVIS_BUILD_DIR/oscm-build/cruisecontrol.xml runTravisUT
#  - ant -lib $TRAVIS_BUILD_DIR/libraries/apache-ant-contrib/javalib -file $TRAVIS_BUILD_DIR/oscm-build/cruisecontrol.xml runTravisIT
after_script:
  - codecov
